name: RSS to CSV Daily Update

on:
  schedule:
    # Run daily at 9:00 AM JST (00:00 UTC)
    - cron: '0 0 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  fetch-rss:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Download previous CSV artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: rss-to-csv.yml
          name: rss-feed-data
          path: .
          if_no_artifact_found: ignore

      - name: Fetch RSS feeds and update CSV
        run: bun index.ts

      - name: Upload CSV as artifact
        uses: actions/upload-artifact@v4
        with:
          name: rss-feed-data
          path: output.csv
          retention-days: 90
